Repository hamler-lang/documentation, pull requests merged in 2020-06, with the labels that each got.

#23 docs: create 'book', 'courses' and 'design' folders
  book/README
  courses/README
  design/README
Labels: enhancement

#24 docs(guides): add more chapters
  guides/DataTypesMapping.md
  guides/DifferencesWithHaskell.md
  guides/DifferencesWithPurescript.md
Labels: documentation

#25 docs(book): a draft for the book
  book/Behaviours.md
  book/Behaviours/GenEvent.md
  book/Behaviours/GenServer.md
  book/Behaviours/GenStatem.md
  book/Behaviours/Supervisor.md
  book/Control/Monad.md
  book/DataTypes.md
  book/DataTypes/AlgebraicDataTypes.md
  book/DataTypes/BasicTypes.md
  book/DataTypes/Binaries.md
  book/DataTypes/Lists.md
  book/DataTypes/Maps.md
  book/DataTypes/Records.md
  book/Databases.md
  book/Databases/ETS.md
  book/Databases/Mnesia.md
  book/Distribution.md
  book/ERTS.md
  book/ERTS/Atomics.md
  book/Exceptions.md
  book/Expressions.md
  book/Expressions/CaseOf.md
  book/Expressions/Guards.md
  book/Expressions/IfElse.md
  book/Expressions/LetIn.md
  book/Expressions/Operators.md
  book/Expressions/Where.md
  book/Functions.md
  book/Installation.md
  book/Introduction.md
  book/Lambda.md
  book/ListComprehensions.md
  book/Modules.md
  book/PatternMatch.md
  book/Process.md
  book/REPL.md
  book/Recursion.md
  book/SendRecv.md
  book/Sockets.md
  book/Sockets/CoAP.md
  book/Sockets/Inet.md
  book/Sockets/MQTT.md
  book/Sockets/QUIC.md
  book/Sockets/TCP.md
  book/Sockets/UDP.md
  book/TypeClass.md
  book/Types.md
  courses/README
  design/ReservedWords.md
Labels: documentation

#28 docs(FAQ): fix typo
  FAQ.md
Labels: documentation

#31 docs(Cheatsheet): update Cheatsheet
  Cheatsheet.md
Labels: documentation, enhancement

#32 docs(book): fix typo and add 'Distribution' chapter
  book/Distribution/RPC.md
  book/Functions.md
Labels: documentation

#34 docs(Cheatsheet): update Cheatsheet.md
  Cheatsheet.md
Labels: documentation, enhancement

#38 docs(Concurrenct): add 'Message Passing' paragraph
  guides/ProcessAndConcurrency.md
Labels: documentation

#39 docs(guides): finish the 'Data Types Mapping' chapter
  guides/DataTypesMapping.md
Labels: documentation

#40 docs(guides): add chapter 'Differences From Erlang'
  guides/DifferencesFromErlang.md
  guides/ProcessAndConcurrency.md
Labels: documentation

#42 docs(guides): finished chapter 'DifferencesFromErlang'
  guides/DifferencesFromErlang.md
Labels: documentation

#43 docs(cheatsheet): add keyword 'otherwise'
  Cheatsheet.md
Labels: documentation

#44 docs(guides): adjusts chapters
  guides/08_ForeignFunctionInterface.md
  guides/09_DataTypesMapping.md
  guides/10_ProcessAndConcurrency.md
  guides/11_OTPBehaviours.md
  guides/12_NodeAndDistribution.md
  guides/13_DifferencesFromErlang.md
  guides/14_DifferencesFromHaskell.md
  guides/15_DifferencesFromPurescript.md
  guides/ConcurrentAndDistribution.md
Labels: documentation

#46 docs(guides): update README and add ToC of Guides
  README.md
  guides/00_TableOfContents.md
  guides/01_WhyHamler.md
  guides/02_QuickStart.md
  guides/03_BasicTypesFunctionsAndOperators.md
  guides/04_MoreTypesandPatternMatching.md
  guides/05_HigherOrderFunctionsAndRecursions.md
  guides/06_TypeClasses.md
  guides/07_ApplicativeAndMonad.md
  guides/08_ForeignFunctionInterface.md
  guides/10_ProcessAndConcurrency.md
  guides/11_OTPBehaviours.md
  guides/12_NodeAndDistribution.md
  guides/13_DifferencesFromErlang.md
  guides/14_DifferencesFromHaskell.md
  guides/15_DifferencesFromPurescript.md
Labels: documentation

#49 docs(README): update ToC of FFI chapter
  README.md
Labels: documentation

#50 docs(guides): update chapter 'ProcessAndConcurrency'
  guides/10_ProcessAndConcurrency.md
Labels: documentation

#53 Update 14_DifferencesFromHaskell.md
  guides/14_DifferencesFromHaskell.md
Labels: enhancement
