Repository hamler-lang/documentation, pull requests merged in 2020-08, with the labels that each got.

#61 docs(OTPBehaviours): add chapter '11_OTPBehaviours'
  guides/10_ProcessAndConcurrency.md
  guides/11_OTPBehaviours.md
Labels: documentation

#62 docs(guides): add chapter 10 - Message Passing Concurrency
  guides/10_MessagePassingConcurrency.md
  guides/10_ProcessAndConcurrency.md
Labels: enhancement

#63 docs(guides): add a first draft of chapter 10
  guides/12_NodeAndDistributedErlang.md
  guides/12_NodeAndDistribution.md
Labels: documentation

#64 docs(README): update links to chapter 10, 11, and 12
  README.md
  guides/11_OTPBehaviours.md
Labels: documentation

#65 fix(README): fix broken links
  README.md
Labels: documentation

#66 fix: change syntax of record update
  Cheatsheet.md
  guides/03_BasicTypesFunctionsAndOperators.md
Labels: enhancement

#68 fix(chapter12): fix grammatical errors
  guides/12_NodeAndDistributedErlang.md
Labels: bug

#70 fix(Cheatsheet): add 'after' keyword
  Cheatsheet.md
Labels: documentation

#72 fix(chapter10): update sample code
  guides/10_MessagePassingConcurrency.md
Labels: documentation

#74 fix(guides): remove 'import Control.Precess (getSelf)'
  guides/01_WhyHamler.md
Labels: enhancement

#75 fix(guides): refactor function loop
  guides/01_WhyHamler.md
Labels: enhancement
